### ISSUE TITLE
localhost端口 不能hard code 成 1080，最好从用户自定义的json 配置文件里读取

### ISSUE THREAD

**Issue by zhanglianbo35** [the0demiurge/MyScripys-linux#10]
有些用户的local host 端口 并不一定是 1080（当然大部分的是）

ssr_test(){
    echo Testing Connection...
    curl cip.cc **--socks5 'localhost:1080'**
    if [ $? == 0 ]; then echo -e '\nChecking delay...'; tsocks ping -c 5 cip.cc; fi
}

**Comment by the0demiurge** [comment]
已使用jq提取端口
