### ISSUE TITLE
Ubuntu 17.04 默认并没有安装 tsock

### ISSUE THREAD

**Issue by zhanglianbo35** [the0demiurge/MyScripys-linux#11]
作者可否加个判断 ，是否机子上已经装过 tsock ？ 如果没安装 提示user 运行 apt-get install tsocks ？

**Comment by zhanglianbo35** [comment]
即使装了 tsocks，  也会报错 ERROR: ld.so: object 'libtsocks.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by the0demiurge** [comment]
依赖库没装上的原因未知，tsocks的问题我年后再解决吧

**Comment by the0demiurge** [comment]
已解决
