### ISSUE TITLE
怎么开全局代理？

### ISSUE THREAD

**Issue by Knaithe** [the0demiurge/MyScripys-linux#12]
我成功配置了ssr，在浏览器里用的manual proxy也可以翻出去，如果我想全局怎么弄？我设置network setting为
<img width="486" alt="default" src="https://user-images.githubusercontent.com/22469662/36522023-0caee2a4-17d5-11e8-8931-373f44433355.PNG">
然后在浏览器里设置为use system proxy setting,然后就上不了网了,开不了全局吗？
有什么方法，谢谢！

**Comment by Sung-yy** [comment]
能全局ma ?

**Comment by Sung-yy** [comment]
我说的是ssr。

**Comment by the0demiurge** [comment]
命令行软件是无法直接使用socks代理的，你需要结合tsocks使用

**Comment by alwxkxk** [comment]
具体可以找tsocks或proxychains代理的文章。 @Sung-yy
