### ISSUE TITLE
连接错误，

### ISSUE THREAD

**Issue by Knaithe** [the0demiurge/MyScripys-linux#14]
parse error: Invalid numeric literal at line 17, column 32
curl: (7) Failed to connect to localhost port 0: Connection refused
刚装的debian9.4,貌似是不能访问本地端口？

**Comment by Knaithe** [comment]
应该不是防火墙的问题吧?

**Comment by the0demiurge** [comment]
ssr配置文件写错了，第17行32列

**Comment by Knaithe** [comment]
1.我也没看出问题出在哪里？第17行：WEBSITE=http://ss.pythonic.life，唯一调用$WEBSITE的地方是 
   ssr_update函数，但是我启动ssr的时候没有直接也没有间接调用ssr_update，我用的自己的ssr账号。
2.curl: (7) Failed to connect to localhost port 0: Connection refused，访问本地端口失败，后面的0：是指错误代码？

**Comment by the0demiurge** [comment]
用ssr shell到ssr配置文件夹，看看config.json有没有什么错误吧

**Comment by Knaithe** [comment]
1. 我看config.json没毛病吧，我配置了不止一次了，无非就是ip，端口，密码，加密方式，协议，混淆方式，其他的我都没动。
2.ssr能用，虽然有上面的报错，并不影响daili运行，只是你写的ssr脚本出了没毛病，每次链接都应该有链接状态，出了上面的问题后就没有了。

**Comment by the0demiurge** [comment]
不影响使用大概就没问题，我用jq提取的config.JSON本地端口，由于某些原因没找到端口

**Comment by ghost** [comment]
把config.json里下面两行代码注释掉

`"additional_ports" : {}, // only works under multi-user mode`
`"additional_ports_only"`` : false, // only works under multi-user mode`
