### ISSUE TITLE
checkdelay的步骤报出libtsocks.so错误

### ISSUE THREAD

**Issue by zhangyiw** [the0demiurge/MyScripys-linux#16]
ERROR: ld.so: object 'libtsocks.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by zhangyiw** [comment]
完整输出
IPv6 support
2018-05-02 08:31:01 INFO     util.py:85 loading libcrypto from libcrypto.so.1.1
started
Testing Connection...
{
  "ip": "xxx",
  "hostname": "xxx",
  "city": "Tokyo",
  "region": "Tokyo",
  "country": "JP",
  "loc": "35.6850,139.7510",
  "postal": "190-0031",
  "org": "AS63949 Linode, LLC"
}
Checking delay...
ERROR: ld.so: object 'libtsocks.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
PING cip.cc (120.27.134.98) 56(84) bytes of data.
64 bytes from 120.27.134.98 (120.27.134.98): icmp_seq=1 ttl=49 time=27.7 ms
64 bytes from 120.27.134.98 (120.27.134.98): icmp_seq=2 ttl=49 time=26.6 ms
64 bytes from 120.27.134.98 (120.27.134.98): icmp_seq=3 ttl=49 time=27.9 ms
64 bytes from 120.27.134.98 (120.27.134.98): icmp_seq=4 ttl=49 time=28.7 ms
64 bytes from 120.27.134.98 (120.27.134.98): icmp_seq=5 ttl=49 time=27.7 ms

--- cip.cc ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4004ms
rtt min/avg/max/mdev = 26.652/27.761/28.705/0.656 ms

**Comment by the0demiurge** [comment]
应该是因为你的tsocks没装好，不过实际上也没什么影响

**Comment by zhangyiw** [comment]
确实不影响使用，那就没太大关系了
