### ISSUE TITLE
有关linux酸酸乳一键脚本

### ISSUE THREAD

**Issue by dyqnaruto** [the0demiurge/MyScripys-linux#17]
最近无聊搞点东西，需要用到linux ssr客户端，我的系统是centos7_64，我发现运行一键脚本中61和62行会报错
61:**jq** ".local_port" $INSTALL_PATH/config.json
62:**tsocks** ping -c 5 cip.cc;
原因是centos7没有自带jq和tsocks，前者我通过从官网上下载可执行的jq，添加环境变量后解决；后者yum源没有，安装起来也很复杂，只能通过编译安装，但安装时提示缺少libtsocks.so很尴尬。
最后是通过改host解决的问题，请问老徐可以增加对centos支持吗，谢谢！

**Comment by the0demiurge** [comment]
jq和tsocks都只是测试ssr是否有效的，其实完全不影响使用，把出错的行直接删掉也没关系；
我一会对这些依赖修改一下，如果没依赖的话做一些提示吧

**Comment by the0demiurge** [comment]
已解决
