### ISSUE TITLE
config文件都需要配置那些参数啊

### ISSUE THREAD

**Issue by javaeryang** [the0demiurge/MyScripys-linux#18]
配置了也无效[
![ssr](https://user-images.githubusercontent.com/27242250/41806824-6870cfc2-76f7-11e8-9592-1b4b3eac0429.png)
](url)

**Comment by javaeryang** [comment]
配置了服务器，端口，密码，加密方法，四个参数，但就是不生效。

**Comment by the0demiurge** [comment]
使用 ssr log 看一下日志就知道哪里出问题了

**Comment by RideWindOne** [comment]
感谢大神，正常运行了可以访问国内网站了。

**Comment by byYufeng** [comment]
如果报错  parse error: Invalid numeric literal 的话把斜杠那两行删掉
