### ISSUE TITLE
ubuntu16.04链接上以后，设置127.0.0.1:1080仍然无法翻墙

### ISSUE THREAD

**Issue by wuguowei1994** [the0demiurge/MyScripys-linux#2]
看log估计已经连上了，但是把chrome设置127.0.0.1:1080后，仍然无法翻墙，是不是还有哪里要设置一下？
ssr config命令后，控制台打印：
--------------------------------------------------------------------------------------------
IPv6 support
stopped
IPv6 support
2017-10-12 15:51:51 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
started
Testing Connection...
当前 IP：45.76.172.148 来自：美国 Vultr
--------------------------------------------------------------------------------------------
看样子连上了，但是设置代理后，仍然无法访问google。
PS:同样的SSR客户端配置，在windws可以，在ubuntu16.04失败了，因为我用的双系统。

**Comment by wuguowei1994** [comment]
使用netstat -apn | grep 1080 命令查看端口1080的使用情况，控制台打印：
------------------------------------------------------------------------------------------------------------------
tcp        0      0 127.0.0.1:1080          0.0.0.0:*               LISTEN      6397/python     
udp        0      0 127.0.0.1:1080          0.0.0.0:*                           6397/python 
------------------------------------------------------------------------------------------------------------------
说明1080端口被监听了。

**Comment by the0demiurge** [comment]
Merged to #1
