### ISSUE TITLE
ERROR: ld.so: 

### ISSUE THREAD

**Issue by P-Zhu** [the0demiurge/MyScripys-linux#20]
Checking delay...
ERROR: ld.so: object 'libtsocks.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by byYufeng** [comment]
+1
我还以为我centos环境的问题
还有server启动之后怎么使用？ 直接ping google依然不通

**Comment by the0demiurge** [comment]
1. 应该是因为tsocks没装好或者没配置好，这个不影响，只是用来检测ssr通不通的
2. 启动后要让终端走代理才行，比如用tsocks或者其他方案
