### ISSUE TITLE
Ask a question about using a branch

### ISSUE THREAD

**Issue by yefeiyu** [the0demiurge/MyScripys-linux#22]
I saw that akkariiin/Experimental's branch with recent updates, why we didn't use it?
I modified this:
```
WEBSITE=http://ss.pythonic.life
BRANCH=akkariiin/Experimental
GIT_REPO=https://github.com/shadowsocksrr/shadowsocksr.git
INSTALL_PATH=$HOME/.local/share/shadowsocksr
```
but there has an error.

**Comment by the0demiurge** [comment]
Because I'm not familiar with that branch, you can change it yourself:)
