### ISSUE TITLE
problem: ssr config  report  curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by weilain** [the0demiurge/MyScripys-linux#23]
ssr config  File configuration

```
{
    "server": "144.34.130.252",
    "server_ipv6": "::",
    "server_port": 443,
    "local_address": "127.0.0.1",
    "local_port": 1080,

    "password": "0EnvPk6moOXC",
    "method": "aes-128-cfb,
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth_compatible",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

    "additional_ports" : {},
    "additional_ports_only" :false,
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 0,
    "redirect": "",
    "fast_open": false
}
```

**Comment by the0demiurge** [comment]
That’s usually because your ssr account have been blocked

weilain <notifications@github.com>于2018年12月6日 周四下午5:11写道：

**Comment by weilain** [comment]
![image](https://user-images.githubusercontent.com/42827119/49574393-4cd32600-f97b-11e8-9a96-6bd14e5a488f.png)
Is normally used

**Comment by the0demiurge** [comment]
Then you can ignore that message

weilain <notifications@github.com>于2018年12月6日 周四下午5:21写道：

**Comment by weilain** [comment]
So what should I do?

**Comment by the0demiurge** [comment]
Just ignore that error message,it’s okay.

weilain <notifications@github.com>于2018年12月6日 周四下午5:27写道：

**Comment by weilain** [comment]
![image](https://user-images.githubusercontent.com/42827119/49575075-c9b2cf80-f97c-11e8-8467-888e68585570.png)
But ping google does not work

**Comment by the0demiurge** [comment]
You should make sure that ping is over ssr, for example by using
 proxychains.

weilain <notifications@github.com>于2018年12月6日 周四下午5:32写道：

**Comment by weilain** [comment]
do not understand

**Comment by the0demiurge** [comment]
You should configure proxychains correctly and use `proxychains ping` instead of ping.
