### ISSUE TITLE
archlinux    

### ISSUE THREAD

**Issue by hehh2001** [the0demiurge/MyScripys-linux#25]
ERROR    encrypt.py:94 method aes-256-gcm not supported

**Comment by hehh2001** [comment]
python2-m2crypto    have   install     python-m2crypto  have  install  too

**Comment by the0demiurge** [comment]
Install shadowsocksr which supports that crypt method to $HOME/.local/share/shadowsocksr would help.

**Comment by hehh2001** [comment]
Thank you. I have successfully configured the proxy, but there is still an error.
util.py:85 loading libcrypto from libcrypto.so.1.1
started

**Comment by hehh2001** [comment]
Has not affected the use, thank you very much, it is very compact and convenient!!!
