### ISSUE TITLE
ssr install issue

### ISSUE THREAD

**Issue by VegeBun-csj** [the0demiurge/MyScripys-linux#26]
after "ssr install"
post the issue
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.11
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
terminate called after throwing an instance of 'apf::JackClient::jack_error'
  what():  JackClient: Unable to connect to the JACK server!

**Comment by the0demiurge** [comment]
Probably because of issues of network, permissions or git.

**Comment by Theo-Wu** [comment]
why sudo:git:cannot find the command

**Comment by the0demiurge** [comment]
You need install git first

**Comment by Theo-Wu** [comment]
i think the problem has been eliminated and thank you

**Comment by the0demiurge** [comment]
You are welcome :)
