### ISSUE TITLE
ssr EDITOR check

### ISSUE THREAD

**Issue by HoshinoTented** [the0demiurge/MyScripys-linux#27]
错误信息:
```
.local/bin/ssr: 第 13 行: [: emacsclient: 需要二元表达式
```

**~/.bashrc**:
```
export EDITOR="emacsclient -nw"
```

看起来是没有加双引号的缘故

**Comment by the0demiurge** [comment]
已添加双引号@https://github.com/the0demiurge/CharlesScripts/commit/feb0685dc0b781ca5dcfe36453af27c665dc8dbc
