### ISSUE TITLE
使用同一个节点配置，windows下可以，linux下不行

### ISSUE THREAD

**Issue by supercoos** [the0demiurge/MyScripys-linux#28]
执行了SSR INSTALL
SSR CONFIG

IP      : 185.173.93.100
地址    : 俄罗斯  新西伯利亚州  新西伯利亚
运营商  : clx.ru

数据二  : 俄罗斯

数据三  : 荷兰

URL     : http://www.cip.cc/185.173.93.100
You may install proxychains4 and configure it properly to test net delay
[root@localhost pei2]# ping www.google.com
PING www.google.com (31.13.73.17) 56(84) bytes of data.
^C
--- www.google.com ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9000ms

**Comment by ubbcou** [comment]
同状况，希望得到解答。
谢谢～
:)

**Comment by the0demiurge** [comment]
要看日志才知道原因

**Comment by ubbcou** [comment]
@the0demiurge 
谢谢。
我是个linux新手。
现在我知道我的原因了，除了开启ss client，我还需要设置网络代理：将socks主机设置：127.0.0.1:1080。
这个是全局代理吧，还有个pac模式更麻烦些。
是这样的吧。
:D

**Comment by weekendyy** [comment]
我也是碰到了同样的状况，我再ssr config里面配置不是已经有配置1080端口了吗，还需要再哪里配置吗

**Comment by weekendyy** [comment]
> @the0demiurge 谢谢。 我是个linux新手。 现在我知道我的原因了，除了开启ss client，我还需要设置网络代理：将socks主机设置：127.0.0.1:1080。 这个是全局代理吧，还有个pac模式更麻烦些。 是这样的吧。 :D

我也是新手，第一次碰到，请问 将socks主机设置：127.0.0.1:1080 这个步骤是在哪里设置的呢，我在ssr config 里面已经有设置了
