### ISSUE TITLE
[ssr script] Not working on Ubuntu 17.1, please advise how to fix this

### ISSUE THREAD

**Issue by OutGazing** [the0demiurge/MyScripys-linux#3]
here below is the output after inputting "ssr start" with super user privilege [the proxy info in the configure file("~/.local/share/shadowsocksr/config.json") is correct and effective for sure] :

```
2017-11-21 19:04:53 INFO     util.py:85 loading libsodium from libsodium.so.18
started
Testing Connection...
curl: (52) Empty reply from server


```

**Comment by the0demiurge** [comment]
It seems there are some issues in your config file, try `ssr config` and check or edit your configuration:)

Or you may try config files from [ss.pythonic.life/json](http://ss.pythonic.life/json)

**Comment by OutGazing** [comment]
Thanks for your reply, but it still failed to take effect.
I reinstalled it, input "ssr update" into the terminal, and the output is as follows:`~# ssr update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    68  100    68    0     0     68      0  0:00:01 --:--:--  0:00:01    71
curl: (7) Failed to connect to gentle-oasis-59484.herokuapp.com port 443: Connection refused
`

**Comment by the0demiurge** [comment]
The webpage was blocked, and you can edit the `$WEBSITE` in `ssr` script to a new url.

For more information, see [ShadowsocksShare-OpenShift#17](https://github.com/the0demiurge/ShadowSocksShare-OpenShift/issues/17)

**Comment by OutGazing** [comment]
It turned out to be something wrong with the format of the config JSON file. All set, good to go. Thanks for your patience and reply, though.
