### ISSUE TITLE
windows/Android都可以使用的配置，但是ubuntu的客户端不可以

### ISSUE THREAD

**Issue by daxin09pp** [the0demiurge/MyScripys-linux#30]
root@avepoint:~/.local/share/shadowsocksr# ssr config
IPv6 support
stopped
IPv6 support
2019-07-01 11:02:06 INFO     util.py:85 loading libcrypto from libcrypto.so.1.1
started
Testing Connection...
jq in use
connection information:
curl: (52) Empty reply from server

shadowsocksr.log会报如下错误：
2019-07-01 11:02:06 INFO     local.py:50 local start with protocol[auth_sha1_v4_compatible] password [xxxxxxxx] method [aes-256-cfb] obfs [http_simple_compatible] obfs_param []
2019-07-01 11:02:06 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-07-01 11:02:06 INFO     asyncdns.py:324 dns server: [('127.0.0.53', 53)]
2019-07-01 11:02:07 INFO     tcprelay.py:643 TCP request 216.239.34.21:80 by user 1080
2019-07-01 11:02:07 INFO     tcprelay.py:794 TCP connecting 216.239.34.21(52.221.177.46):80 from 10.1.52.13:45090 by user 1080

会报这个错误，请问我还可以看哪里的log来定位问题，现在这些信息不够定位问题。

**Comment by the0demiurge** [comment]
看不出来有问题，检测连通性的时候curl认为没有连通，但是连接是正常的

**Comment by daxin09pp** [comment]
我用firefox把proxy换成127.0.0.1：1080，访问google，baidu都不行，显示连接超时

**Comment by dguozhenxin8888** [comment]
root@avepoint:~/.local/share/shadowsocksr# netstat -anpt
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:50505         0.0.0.0:*               LISTEN      3522/prosvc         
tcp        0      0 127.0.0.1:7337          0.0.0.0:*               LISTEN      1762/postgres.bin   
tcp        0      0 0.0.0.0:3790            0.0.0.0:*               LISTEN      17900/nginx: master 
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN      2517/dnsmasq        
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      597/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1343/sshd           
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      766/cupsd           
tcp        0      0 127.0.0.1:1080          0.0.0.0:*               LISTEN      20864/python        
tcp        0      0 127.0.0.1:3001          0.0.0.0:*               LISTEN      5226/thin server (1 
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      10339/sshd: avepoin 
tcp        0      0 0.0.0.0:8834            0.0.0.0:*               LISTEN      1616/nessusd        
tcp        0      0 127.0.0.1:7337          127.0.0.1:41744         ESTABLISHED 18028/postgres: msf 
tcp        0      0 127.0.0.1:7337          127.0.0.1:41572         ESTABLISHED 17781/postgres: msf 
tcp        0      0 127.0.0.1:56968         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:56964         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:56962         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:41722         127.0.0.1:7337          ESTABLISHED 3522/prosvc         
tcp        0    212 10.1.52.13:22           10.1.82.58:31304        ESTABLISHED 10046/sshd: avepoin 
tcp        0      0 127.0.0.1:7337          127.0.0.1:41722         ESTABLISHED 17928/postgres: msf 
tcp        0      0 127.0.0.1:41744         127.0.0.1:7337          ESTABLISHED 18021/metasploit_wo 
tcp        0      0 127.0.0.1:41572         127.0.0.1:7337          ESTABLISHED 5226/thin server (1 
tcp        0      0 127.0.0.1:56972         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:7337          127.0.0.1:41576         ESTABLISHED 17784/postgres: msf 
tcp        0      0 127.0.0.1:41576         127.0.0.1:7337          ESTABLISHED 3522/prosvc         
tcp        0      0 127.0.0.1:56970         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:56960         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:56958         127.0.0.1:1080          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:56966         127.0.0.1:1080          TIME_WAIT   -                   
tcp6       0      0 :::22                   :::*                    LISTEN      1343/sshd           
tcp6       0      0 ::1:3350                :::*                    LISTEN      1347/xrdp-sesman    
tcp6       0      0 ::1:631                 :::*                    LISTEN      766/cupsd           
tcp6       0      0 ::1:6010                :::*                    LISTEN      10339/sshd: avepoin 
tcp6       0      0 :::3389                 :::*                    LISTEN      1510/xrdp           
tcp6       0      0 :::4000                 :::*                    LISTEN      1657/gsad           
tcp6       0      0 :::8834                 :::*                    LISTEN      1616/nessusd        
tcp6       0      0 10.1.52.13:3389         10.1.82.58:31300        ESTABLISHED 6022/xrdp

**Comment by dguozhenxin8888** [comment]
{
    "server": "52.221.177.46",
    "server_ipv6": "::",
    "server_port": 80,
    "local_address": "127.0.0.1",
    "local_port": 1080,

    "password": "xxxxxxxx",
    "method": "aes-256-cfb",
    "protocol": "auth_sha1_v4_compatible",
    "protocol_param": "",
    "obfs": "http_simple_compatible",
    "obfs_param": "",
    "speed_limit_per_con": 0,
    "speed_limit_per_user": 0,

    "additional_ports" : {},
    "additional_ports_only" : false,
    "timeout": 120,
    "udp_timeout": 60,
    "dns_ipv6": false,
    "connect_verbose_info": 1,
    "redirect": "",
    "fast_open": false
}

config是这样的。

**Comment by the0demiurge** [comment]
我也不了解，这已经不是我写的脚本的问题了

**Comment by daxin09pp** [comment]
谢谢。
