### ISSUE TITLE
ssr: port 1080 connection refused

### ISSUE THREAD

**Issue by WIll-Xu35** [the0demiurge/MyScripys-linux#31]
Hi,

I used your ssr script and the installation is success. But when I try to do `./ssr test` or `./ssr config`, there is always a error:

This is the output after execute `./ssr test`

> Testing Connection...
> jq in use
> connection information:
> curl: (7) Failed to connect to localhost port 1080: Connection refused

This is the output after execute `./ssr config`

> IPv6 support
> 2019-07-04 17:08:48 ERROR    daemon.py:155 not running
> IPv6 support
> 2019-07-04 17:08:48 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
> started
> Testing Connection...
> jq in use
> connection information:
> curl: (7) Failed to connect to localhost port 1080: Connection refused

Any idea how to solve this problem?

Thanks!

**Comment by the0demiurge** [comment]
It seems because of problem of your ssr configuration.

**Comment by WIll-Xu35** [comment]
You mean the configuration on vps or localhost?

**Comment by WIll-Xu35** [comment]
@the0demiurge 

I uninstalled the ssr client and reinstall it with root permission. Now this error is gone. After configuration, I can see my connection information correctly (at the end of the connection information, there is a line says `./ssr: 60: [: 0: unexpected operator`, not sure if this is the cause of my problem). But still, I cannot access google.com using either firefox or chrome. Is there any configuration needs to be done before ssr can work?

Thanks.

**Comment by the0demiurge** [comment]
The ssr client starts successfully, but you still cannot access Google, this usually because there is a firewall(may be installed on the gateway) banned you accessing your server, or just your browser misconfigured.

I have too little information to figure it out, and this is not a problem of the `ssr` script, so there is few things I can do with your problem.
