### ISSUE TITLE
fatal error:  texfox.com 域名无法解析

### ISSUE THREAD

**Issue by ghost** [the0demiurge/MyScripys-linux#32]
酸酸乳.zip 都无法获取到怎么解
huilliuh1@gmail.com

**Comment by wangeugene** [comment]
WEBSITE=http://ss.pythonic.life
`yz@yz-ubuntu:~$ sudo ssr start
IPv6 support
2019-09-21 09:01:43 INFO     util.py:85 loading libcrypto from libcrypto.so.1.1
started
Testing Connection...
jq in use
parse error: Invalid numeric literal at line 17, column 32
`
> ssr install 以后就这样落。 config文件里没有免费的帐号。 lantern 运行后8787 都不是listen的。

**Comment by the0demiurge** [comment]
本来就不提供免费帐号也不监听蓝灯

**Comment by wangeugene** [comment]
我擦．这两天　ＳＳ　／ＳＳＲ　都被墙掉落．　受不了啊
