### ISSUE TITLE
Invalid numeric literal at line 16,column32

### ISSUE THREAD

**Issue by xieziyan** [the0demiurge/MyScripys-linux#33]
root@ziyan:~# ssr config
IPv6 support
stopped
IPv6 support
2019-09-04 19:50:56 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
started
Testing Connection...
jq in use
parse error: Invalid numeric literal at line 16, column 32
root@ziyan:~#

**Comment by McDifference** [comment]
我遇到了同样的问题。请问您是如何解决的？

**Comment by the0demiurge** [comment]
配置文件中出现了双斜线风格的注释。jq不支持注释，但是不影响使用，jq只是用来在测试网络连通性的时候用来解析配置文件的。
