### ISSUE TITLE
deepin15.11 报错 curl: (7) Unable to receive initial SOCKS5 response.

### ISSUE THREAD

**Issue by 1015770492** [the0demiurge/MyScripys-linux#34]
![深度截图_选择区域_20191127181950](https://user-images.githubusercontent.com/43501801/69715027-824fc100-1142-11ea-8a83-b9d82a0ae8cb.png)
![深度截图_选择区域_20191127182050](https://user-images.githubusercontent.com/43501801/69715107-a4e1da00-1142-11ea-88ae-c61839922e30.png)
![深度截图_选择区域_20191127182126](https://user-images.githubusercontent.com/43501801/69715156-c04ce500-1142-11ea-9baf-1c7b25126df0.png)

**Comment by 1015770492** [comment]
obfs 插件不支持怎么解决

**Comment by the0demiurge** [comment]
这个我也不清楚，得看ssr作者怎么说
