### ISSUE TITLE
https://ss.pythonic.life/json can't replay

### ISSUE THREAD

**Issue by liuzexiazbx** [the0demiurge/MyScripys-linux#38]
https://ss.pythonic.life/json can't replay.and ssr_test() connection information:curl: (52) Empty reply from server
![image](https://github.com/the0demiurge/CharlesScripts/assets/2562357/bf5f8a35-304b-404e-943d-4d8676cba552)

**Comment by the0demiurge** [comment]
the service of ss.pythonic.life is down owing to heroku does not support free hosting service anymore. It’s possible to deploy [this](https://github.com/the0demiurge/ShadowSocksShare) service on your own server or any web hosting service.
