### ISSUE TITLE
Hi some problem while using your script

### ISSUE THREAD

**Issue by zhuangh7** [the0demiurge/MyScripys-linux#9]
I can successfully use the script to connect my ssr server and open the out of wall website. But the question is, after some minutes, if I try to call "ssr stop" it  doesn't work and say

  cd: /home/myID/.local/share/shadowsocksr/shadowsocks/: 没有那个文件或目录

seems that the dir has been removed? But I never do that, can you help me with it? I don't want to reinstall the ssr server every time I reboot my PC. 
Thanks

**Comment by the0demiurge** [comment]
I have no idea why your ssr installation be removed automatically, but you may edit the ssr script https://github.com/the0demiurge/CharlesScripts/blob/eeb1dcd0ab712d93b54a258f3e5748ca0f68857e/charles/bin/ssr#L20 to a safer path where wouldn't be removed automatically.

**Comment by zhuangh7** [comment]
OK 3q very much, I will try it soon and give you some reply.

**Comment by Knaithe** [comment]
wow,why are you fucking saying English，说中文不好吗？

**Comment by the0demiurge** [comment]
Opening issues in English makes it easier for non-Chinese speakers who are finding solutions.
